package fr.geotower.ui.components

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.defaultMinSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Autorenew
import androidx.compose.material3.Button
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.LifecycleResumeEffect
import androidx.work.WorkInfo
import androidx.work.WorkManager
import fr.geotower.R
import fr.geotower.data.db.GeoTowerDatabaseValidator
import fr.geotower.data.outages.OutageGenerationStep
import fr.geotower.data.outages.OutageLocalConfig
import fr.geotower.data.outages.labelRes
import fr.geotower.data.workers.OutageBackgroundScheduler
import fr.geotower.data.workers.OutageGenerationWorker
import fr.geotower.ui.theme.LocalGeoTowerUiStyle
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.text.DateFormat
import java.util.Date
import java.util.Locale

/**
 * Action et état de la récupération LOCALE des pannes : verrou « base ANFR manquante », bouton
 * « mettre à jour maintenant », progression, motif du dernier échec, puis résumé de la dernière
 * récupération réussie (date, total, répartition par opérateur).
 *
 * Partagé par les DEUX endroits qui pilotent cette source, pour qu'ils ne divergent jamais :
 *  - [fr.geotower.ui.screens.settings.OutageLocalControls], qui y ajoute les réglages d'exécution
 *    (fréquence, arrière-plan) dans l'écran Traitement local ;
 *  - [OutageDownloadCard], qui prend ce contenu quand les pannes sont préparées sur l'appareil : la
 *    carte de la section « Base de données » devient alors une carte de génération plutôt que de
 *    proposer un téléchargement serveur qui ne servirait à rien.
 *
 * La progression est lue sur les DEUX travaux (bouton et planification périodique) pour refléter une
 * récupération quelle que soit son origine.
 */
@Composable
fun OutageLocalGenerationControls(modifier: Modifier = Modifier) {
    val context = LocalContext.current
    val sizing = LocalGeoTowerUiStyle.current.sizing

    val config = remember { OutageLocalConfig(context) }
    var lastGenerated by remember { mutableStateOf(config.lastGeneratedAtMillis) }
    var lastCount by remember { mutableStateOf(config.lastGeneratedCount.takeIf { it >= 0 }) }
    var breakdown by remember { mutableStateOf(config.lastBreakdown) }

    // Le résumé vient des prefs (écrites par LocalOutageProvider), pas de l'outputData du worker :
    // il reste donc affiché après une génération automatique, une régénération paresseuse ou un
    // simple retour sur la page.
    fun refreshLastGeneration() {
        lastGenerated = config.lastGeneratedAtMillis
        lastCount = config.lastGeneratedCount.takeIf { it >= 0 }
        breakdown = config.lastBreakdown
    }

    val workManager = remember { WorkManager.getInstance(context) }
    val oneShotInfos by workManager
        .getWorkInfosForUniqueWorkFlow(OutageBackgroundScheduler.UNIQUE_ONESHOT_WORK)
        .collectAsState(initial = emptyList())
    val periodicInfos by workManager
        .getWorkInfosForUniqueWorkFlow(OutageBackgroundScheduler.UNIQUE_PERIODIC_WORK)
        .collectAsState(initial = emptyList())
    val oneShotInfo = oneShotInfos.lastOrNull()
    val periodicInfo = periodicInfos.lastOrNull()
    // Un travail périodique reste ENQUEUED entre deux exécutions : seul RUNNING = génération en cours.
    val workInfo = periodicInfo?.takeIf { it.state == WorkInfo.State.RUNNING }
        ?: oneShotInfo?.takeIf { it.state == WorkInfo.State.RUNNING || it.state == WorkInfo.State.ENQUEUED }
    val running = workInfo != null
    val percent = workInfo?.progress?.getInt(OutageGenerationWorker.KEY_PERCENT, 0) ?: 0
    val stepOrdinal = workInfo?.progress?.getInt(OutageGenerationWorker.KEY_STEP, 0) ?: 0
    val stepDetail = workInfo?.progress?.getString(OutageGenerationWorker.KEY_DETAIL)
    // Raison du dernier échec (source injoignable, base ANFR illisible…). Sans elle, une
    // récupération ratée était indiscernable d'un bouton qui ne fait rien.
    val failureMessage = oneShotInfo
        ?.takeIf { it.state == WorkInfo.State.FAILED }
        ?.outputData
        ?.getString(OutageGenerationWorker.KEY_ERROR)

    // Sans base ANFR installée, la récupération locale n'a rien à quoi rattacher les pannes : le
    // géocodage est ce qui donne son identifiant de station à chaque coupure. On lit donc l'état de
    // la base (hors fil principal : la validation ouvre le fichier) et on verrouille le bouton
    // plutôt que de lancer un travail qui ne peut pas aboutir.
    var dbState by remember { mutableStateOf<GeoTowerDatabaseValidator.LocalDatabaseState?>(null) }
    var dbCheckTick by remember { mutableIntStateOf(0) }
    LaunchedEffect(dbCheckTick) {
        dbState = withContext(Dispatchers.IO) {
            GeoTowerDatabaseValidator.getInstalledDatabaseStatus(context).state
        }
    }
    val databaseReady = dbState == GeoTowerDatabaseValidator.LocalDatabaseState.VALID

    // Fin d'une génération (SUCCEEDED du one-shot, ou retour du périodique à ENQUEUED) → on relit.
    LaunchedEffect(oneShotInfo?.id, oneShotInfo?.state, periodicInfo?.id, periodicInfo?.state) {
        refreshLastGeneration()
    }
    // Génération déclenchée hors worker (cache expiré côté carte/widget) pendant que la page dort,
    // et retour de l'utilisateur après être allé chercher la base : on revérifie les deux.
    LifecycleResumeEffect(Unit) {
        refreshLastGeneration()
        dbCheckTick++
        onPauseOrDispose { }
    }

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(sizing.spacing(12.dp)),
    ) {
        // Base absente ou inutilisable : on le dit AVANT le bouton, qui est grisé juste en dessous.
        // Tant que l'état n'est pas connu (dbState == null), on n'affiche rien pour éviter un
        // avertissement qui clignote au premier rendu.
        when (dbState) {
            GeoTowerDatabaseValidator.LocalDatabaseState.MISSING -> R.string.outage_source_db_missing
            GeoTowerDatabaseValidator.LocalDatabaseState.INVALID -> R.string.outage_source_db_invalid
            else -> null
        }?.let { messageRes ->
            Text(
                text = stringResource(messageRes),
                style = sizing.textStyle(MaterialTheme.typography.bodySmall),
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.error,
            )
        }

        Button(
            onClick = { OutageBackgroundScheduler.generateNow(context) },
            enabled = !running && databaseReady,
            modifier = Modifier.fillMaxWidth().defaultMinSize(minHeight = sizing.component(56.dp)),
            shape = RoundedCornerShape(sizing.component(12.dp)),
        ) {
            Icon(
                Icons.Default.Autorenew,
                contentDescription = null,
                modifier = Modifier.size(sizing.component(24.dp)),
            )
            Spacer(Modifier.width(sizing.spacing(8.dp)))
            Text(
                text = stringResource(
                    if (running) R.string.outage_source_generating else R.string.outage_source_generate_now,
                ),
                fontWeight = FontWeight.Bold,
                style = sizing.textStyle(MaterialTheme.typography.labelLarge),
            )
        }

        if (running) {
            val step = OutageGenerationStep.entries[
                stepOrdinal.coerceIn(0, OutageGenerationStep.entries.lastIndex),
            ]
            val stepLabel = stringResource(step.labelRes())
            val stepText = if (stepDetail.isNullOrBlank()) {
                "$stepLabel — $percent %"
            } else {
                "$stepLabel ($stepDetail) — $percent %"
            }
            Text(
                text = stepText,
                style = sizing.textStyle(MaterialTheme.typography.bodySmall),
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.primary,
            )
        }

        if (!running && !failureMessage.isNullOrBlank()) {
            Text(
                text = stringResource(R.string.outage_source_failed, failureMessage),
                style = sizing.textStyle(MaterialTheme.typography.bodySmall),
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.error,
            )
        }

        val lastText = if (lastGenerated > 0L) {
            val formatted = DateFormat
                .getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT, Locale.getDefault())
                .format(Date(lastGenerated))
            stringResource(R.string.outage_source_last_generated, formatted)
        } else {
            stringResource(R.string.outage_source_never)
        }
        Text(
            text = lastText,
            style = sizing.textStyle(MaterialTheme.typography.bodySmall),
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        lastCount?.let { count ->
            Text(
                text = stringResource(R.string.outage_source_generated_count, count),
                style = sizing.textStyle(MaterialTheme.typography.bodySmall),
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.primary,
            )
        }
        if (breakdown.isNotEmpty()) {
            Column(
                modifier = Modifier.fillMaxWidth(),
                verticalArrangement = Arrangement.spacedBy(sizing.spacing(4.dp)),
            ) {
                breakdown.forEach { (operateur, nombre) ->
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                    ) {
                        Text(
                            text = operateur,
                            style = sizing.textStyle(MaterialTheme.typography.bodyMedium),
                            color = MaterialTheme.colorScheme.onSurface,
                        )
                        Text(
                            text = nombre.toString(),
                            style = sizing.textStyle(MaterialTheme.typography.bodyMedium),
                            fontWeight = FontWeight.Bold,
                            color = MaterialTheme.colorScheme.primary,
                        )
                    }
                }
            }
        }
    }
}
