package fr.geotower.ui.screens.settings

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import androidx.work.WorkInfo
import androidx.work.WorkManager
import fr.geotower.R
import fr.geotower.data.AnfrRepository
import fr.geotower.data.outages.OutageGenerationStep
import fr.geotower.data.outages.OutageLocalConfig
import fr.geotower.data.outages.labelRes
import fr.geotower.data.workers.OutageBackgroundScheduler
import fr.geotower.data.workers.OutageGenerationWorker
import fr.geotower.ui.components.CustomSliderCard
import fr.geotower.ui.components.GeoTowerBackTopBar
import fr.geotower.ui.navigation.rememberSafeBackNavigation
import fr.geotower.ui.theme.LocalGeoTowerUiStyle
import java.text.DateFormat
import java.util.Date
import java.util.Locale

/**
 * Page « Source des pannes » (ouverte depuis Réglages ▸ au-dessus de la section base de données).
 * Choix serveur / génération locale (fichiers opérateurs + géocodage sur l'appareil), fréquence,
 * régénération en arrière-plan, et génération immédiate. La génération passe par
 * [OutageGenerationWorker] (notification live) et sa progression est reflétée ici en direct.
 */
@Composable
fun OutageSourceScreen(
    navController: NavController,
    repository: AnfrRepository,
) {
    val context = LocalContext.current
    val uiStyle = LocalGeoTowerUiStyle.current
    val sizing = uiStyle.sizing
    val useOneUi = uiStyle.useOneUi
    val shape = uiStyle.cardShape
    val border = uiStyle.cardBorder
    val bubbleColor = uiStyle.bubbleColor
    val safeBack = rememberSafeBackNavigation(navController, fallbackRoute = "settings")

    val config = remember { OutageLocalConfig(context) }
    var useLocal by remember { mutableStateOf(config.useLocalSource) }
    var frequency by remember { mutableIntStateOf(config.frequencyHours) }
    var background by remember { mutableStateOf(config.backgroundEnabled) }
    var lastGenerated by remember { mutableStateOf(config.lastGeneratedAtMillis) }
    var lastCount by remember { mutableStateOf<Int?>(null) }
    var lastBreakdown by remember { mutableStateOf<String?>(null) }

    BackHandler(enabled = !safeBack.isLocked) { safeBack.navigateBack() }

    // Observe le worker « Générer maintenant » pour refléter la progression et le résultat.
    val workManager = remember { WorkManager.getInstance(context) }
    val workInfos by workManager
        .getWorkInfosForUniqueWorkFlow(OutageBackgroundScheduler.UNIQUE_ONESHOT_WORK)
        .collectAsState(initial = emptyList())
    val workInfo = workInfos.lastOrNull()
    val running = workInfo?.state == WorkInfo.State.RUNNING || workInfo?.state == WorkInfo.State.ENQUEUED
    val percent = workInfo?.progress?.getInt(OutageGenerationWorker.KEY_PERCENT, 0) ?: 0
    val stepOrdinal = workInfo?.progress?.getInt(OutageGenerationWorker.KEY_STEP, 0) ?: 0
    val stepDetail = workInfo?.progress?.getString(OutageGenerationWorker.KEY_DETAIL)

    LaunchedEffect(workInfo?.id, workInfo?.state) {
        if (workInfo?.state == WorkInfo.State.SUCCEEDED) {
            val count = workInfo.outputData.getInt(OutageGenerationWorker.KEY_COUNT, -1)
            if (count >= 0) lastCount = count
            lastBreakdown = workInfo.outputData.getString(OutageGenerationWorker.KEY_BREAKDOWN)
            lastGenerated = config.lastGeneratedAtMillis
        }
    }

    val frequencySteps = remember {
        (OutageLocalConfig.MIN_FREQUENCY_HOURS..OutageLocalConfig.MAX_FREQUENCY_HOURS).toList()
    }
    val frequencyLabels = frequencySteps.map { context.getString(R.string.outage_source_frequency_unit, it) }

    Scaffold(
        containerColor = uiStyle.backgroundColor,
        topBar = {
            GeoTowerBackTopBar(
                title = stringResource(R.string.outage_source_settings_title),
                onBack = { safeBack.navigateBack() },
                backEnabled = !safeBack.isLocked,
            )
        },
    ) { padding ->
        Column(
            modifier = Modifier
                .padding(padding)
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(sizing.spacing(16.dp)),
            verticalArrangement = Arrangement.spacedBy(sizing.spacing(12.dp)),
        ) {
            Text(
                text = stringResource(R.string.outage_source_intro),
                style = sizing.textStyle(MaterialTheme.typography.bodyMedium),
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )

            PreferenceSwitchCard(
                title = stringResource(R.string.outage_source_mode_title),
                desc = stringResource(R.string.outage_source_mode_desc),
                checked = useLocal,
                onCheckedChange = {
                    useLocal = it
                    config.useLocalSource = it
                    OutageBackgroundScheduler.reconcile(context)
                },
                shape = shape, border = border, bubbleColor = bubbleColor, useOneUi = useOneUi,
            )

            CustomSliderCard(
                title = stringResource(R.string.outage_source_frequency_title),
                currentValue = frequency,
                steps = frequencySteps,
                labels = frequencyLabels,
                onValueChange = {
                    frequency = it
                    config.frequencyHours = it
                    OutageBackgroundScheduler.reconcile(context)
                },
                shape = shape, border = border, bubbleColor = bubbleColor, useOneUi = useOneUi,
                footerText = stringResource(R.string.outage_source_frequency_footer),
                enabled = useLocal,
            )

            PreferenceSwitchCard(
                title = stringResource(R.string.outage_source_background_title),
                desc = stringResource(R.string.outage_source_background_desc),
                checked = background,
                onCheckedChange = {
                    background = it
                    config.backgroundEnabled = it
                    OutageBackgroundScheduler.reconcile(context)
                },
                shape = shape, border = border, bubbleColor = bubbleColor, useOneUi = useOneUi,
            )

            Spacer(Modifier.height(sizing.spacing(4.dp)))

            Button(
                onClick = { OutageBackgroundScheduler.generateNow(context) },
                enabled = useLocal && !running,
                modifier = Modifier.fillMaxWidth(),
            ) {
                Text(
                    stringResource(
                        if (running) R.string.outage_source_generating else R.string.outage_source_generate_now,
                    ),
                )
            }

            if (running) {
                val step = OutageGenerationStep.entries[
                    stepOrdinal.coerceIn(0, OutageGenerationStep.entries.lastIndex),
                ]
                val stepLabel = stringResource(step.labelRes())
                val stepText = if (stepDetail.isNullOrBlank()) {
                    "$stepLabel — $percent %"
                } else {
                    "$stepLabel ($stepDetail) — $percent %"
                }
                Text(
                    text = stepText,
                    style = sizing.textStyle(MaterialTheme.typography.bodySmall),
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.primary,
                )
            }

            val lastText = if (lastGenerated > 0L) {
                val formatted = DateFormat
                    .getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT, Locale.getDefault())
                    .format(Date(lastGenerated))
                stringResource(R.string.outage_source_last_generated, formatted)
            } else {
                stringResource(R.string.outage_source_never)
            }
            Text(
                text = lastText,
                style = sizing.textStyle(MaterialTheme.typography.bodySmall),
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
            lastCount?.let { count ->
                Text(
                    text = stringResource(R.string.outage_source_generated_count, count),
                    style = sizing.textStyle(MaterialTheme.typography.bodySmall),
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.primary,
                )
            }
            lastBreakdown?.takeIf { it.isNotBlank() }?.let { breakdown ->
                Text(
                    text = breakdown,
                    style = sizing.textStyle(MaterialTheme.typography.bodySmall),
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        }
    }
}
